### ISSUE TITLE
Error in airflow pipeline

### ISSUE THREAD

**Issue by marcogarieri** [EST-Team-Adam/TheReadingMachine#23]
I faced the same problem after several try of TheReadingMachine airflow pipeline.
Here for reference I attach the log of the error, and I think it is due to memory. If this is the case, this means a MacOS with 8GB RAM is not enough for the pipeline.

```
[2017-05-28 22:32:31,774] {models.py:167} INFO - Filling up the DagBag from /Users/marcogarieri/Documents/TheReadingMachine/airflow/dags/the_reading_machine.py
[2017-05-28 22:32:31,919] {base_task_runner.py:112} INFO - Running: ['bash', '-c', u'airflow run the_reading_machine topic_modelling 2017-05-28T11:10:53.339861 --job_id 7 --raw -sd DAGS_FOLDER/the_reading_machine.py']
[2017-05-28 22:32:32,235] {base_task_runner.py:95} INFO - Subtask: [2017-05-28 22:32:32,235] {__init__.py:57} INFO - Using executor SequentialExecutor
[2017-05-28 22:32:32,903] {base_task_runner.py:95} INFO - Subtask: [2017-05-28 22:32:32,903] {models.py:167} INFO - Filling up the DagBag from /Users/marcogarieri/Documents/TheReadingMachine/airflow/dags/the_reading_machine.py
[2017-05-28 22:32:33,051] {base_task_runner.py:95} INFO - Subtask: [2017-05-28 22:32:33,051] {models.py:1126} INFO - Dependencies all met for <TaskInstance: the_reading_machine.topic_modelling 2017-05-28 11:10:53.339861 [queued]>
[2017-05-28 22:32:33,056] {base_task_runner.py:95} INFO - Subtask: [2017-05-28 22:32:33,056] {models.py:1126} INFO - Dependencies all met for <TaskInstance: the_reading_machine.topic_modelling 2017-05-28 11:10:53.339861 [queued]>
[2017-05-28 22:32:33,057] {base_task_runner.py:95} INFO - Subtask: [2017-05-28 22:32:33,056] {models.py:1318} INFO - 
[2017-05-28 22:32:33,057] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2017-05-28 22:32:33,057] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 4
[2017-05-28 22:32:33,057] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2017-05-28 22:32:33,057] {base_task_runner.py:95} INFO - Subtask: 
[2017-05-28 22:32:33,066] {base_task_runner.py:95} INFO - Subtask: [2017-05-28 22:32:33,066] {models.py:1342} INFO - Executing <Task(BashOperator): topic_modelling> on 2017-05-28 11:10:53.339861
[2017-05-28 22:32:33,080] {base_task_runner.py:95} INFO - Subtask: [2017-05-28 22:32:33,080] {bash_operator.py:71} INFO - tmp dir root location: 
[2017-05-28 22:32:33,080] {base_task_runner.py:95} INFO - Subtask: /var/folders/cj/bf16_zmj5v14v7g8ql0lbv180000gp/T
[2017-05-28 22:32:33,083] {base_task_runner.py:95} INFO - Subtask: [2017-05-28 22:32:33,082] {bash_operator.py:80} INFO - Temporary script location :/var/folders/cj/bf16_zmj5v14v7g8ql0lbv180000gp/T/airflowtmpiXgT1S//var/folders/cj/bf16_zmj5v14v7g8ql0lbv180000gp/T/airflowtmpiXgT1S/topic_modellingNogBoi
[2017-05-28 22:32:33,083] {base_task_runner.py:95} INFO - Subtask: [2017-05-28 22:32:33,083] {bash_operator.py:81} INFO - Running command: python /Users/marcogarieri/Documents/TheReadingMachine/airflow/../pipeline/topic_modelling/processor.py
[2017-05-28 22:32:33,088] {base_task_runner.py:95} INFO - Subtask: [2017-05-28 22:32:33,088] {bash_operator.py:90} INFO - Output:
[2017-05-29 00:34:34,929] {base_task_runner.py:95} INFO - Subtask: [2017-05-29 00:34:34,928] {bash_operator.py:94} INFO - python(80305,0x7fffbbdc63c0) malloc: *** mach_vm_map(size=18446744067307139072) failed (error code=3)
[2017-05-29 00:34:34,932] {base_task_runner.py:95} INFO - Subtask: [2017-05-29 00:34:34,928] {bash_operator.py:94} INFO - *** error: can't allocate region
[2017-05-29 00:34:34,934] {base_task_runner.py:95} INFO - Subtask: [2017-05-29 00:34:34,929] {bash_operator.py:94} INFO - *** set a breakpoint in malloc_error_break to debug
[2017-05-29 00:34:34,964] {base_task_runner.py:95} INFO - Subtask: [2017-05-29 00:34:34,963] {bash_operator.py:94} INFO - /var/folders/cj/bf16_zmj5v14v7g8ql0lbv180000gp/T/airflowtmpiXgT1S/topic_modellingNogBoi: line 1: 80305 Segmentation fault: 11  python /Users/marcogarieri/Documents/TheReadingMachine/airflow/../pipeline/topic_modelling/processor.py
[2017-05-29 00:34:34,964] {base_task_runner.py:95} INFO - Subtask: [2017-05-29 00:34:34,963] {bash_operator.py:97} INFO - Command exited with return code 139
[2017-05-29 00:34:34,965] {base_task_runner.py:95} INFO - Subtask: [2017-05-29 00:34:34,964] {models.py:1417} ERROR - Bash command failed
[2017-05-29 00:34:34,966] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2017-05-29 00:34:34,966] {base_task_runner.py:95} INFO - Subtask:   File "/Users/marcogarieri/Documents/TheReadingMachine/venv/lib/python2.7/site-packages/airflow/models.py", line 1374, in run
[2017-05-29 00:34:34,966] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2017-05-29 00:34:34,966] {base_task_runner.py:95} INFO - Subtask:   File "/Users/marcogarieri/Documents/TheReadingMachine/venv/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 100, in execute
[2017-05-29 00:34:34,966] {base_task_runner.py:95} INFO - Subtask:     raise AirflowException("Bash command failed")
[2017-05-29 00:34:34,966] {base_task_runner.py:95} INFO - Subtask: AirflowException: Bash command failed
[2017-05-29 00:34:34,967] {base_task_runner.py:95} INFO - Subtask: [2017-05-29 00:34:34,966] {models.py:1433} INFO - Marking task as UP_FOR_RETRY
[2017-05-29 00:34:34,976] {base_task_runner.py:95} INFO - Subtask: [2017-05-29 00:34:34,976] {models.py:1462} ERROR - Bash command failed
[2017-05-29 00:34:34,976] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2017-05-29 00:34:34,977] {base_task_runner.py:95} INFO - Subtask:   File "/Users/marcogarieri/Documents/TheReadingMachine/venv/bin/airflow", line 28, in <module>
[2017-05-29 00:34:34,977] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2017-05-29 00:34:34,977] {base_task_runner.py:95} INFO - Subtask:   File "/Users/marcogarieri/Documents/TheReadingMachine/venv/lib/python2.7/site-packages/airflow/bin/cli.py", line 422, in run
[2017-05-29 00:34:34,977] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2017-05-29 00:34:34,978] {base_task_runner.py:95} INFO - Subtask:   File "/Users/marcogarieri/Documents/TheReadingMachine/venv/lib/python2.7/site-packages/airflow/utils/db.py", line 53, in wrapper
[2017-05-29 00:34:34,978] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2017-05-29 00:34:34,978] {base_task_runner.py:95} INFO - Subtask:   File "/Users/marcogarieri/Documents/TheReadingMachine/venv/lib/python2.7/site-packages/airflow/models.py", line 1374, in run
[2017-05-29 00:34:34,978] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2017-05-29 00:34:34,978] {base_task_runner.py:95} INFO - Subtask:   File "/Users/marcogarieri/Documents/TheReadingMachine/venv/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 100, in execute
[2017-05-29 00:34:34,979] {base_task_runner.py:95} INFO - Subtask:     raise AirflowException("Bash command failed")
[2017-05-29 00:34:34,979] {base_task_runner.py:95} INFO - Subtask: airflow.exceptions.AirflowException: Bash command failed
[2017-05-29 00:34:38,721] {jobs.py:2083} INFO - Task exited with return code 1
```

**Comment by marcogarieri** [comment]
Memory requirements are high. Anyway this has been fixed in OSx after correct installation of `requirements.txt`
